[project]
name = "pocket-scion-osc"
version = "1.0.0"
description = "Pocket Scion OSC bridge"
requires-python = ">=3.12"
dependencies = ["python-rtmidi", "python-osc"]

[dependency-groups]
dev = [
    "pyinstaller>=6.19.0",
]
